spring.application.name=multiagent

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini

## Application logging
logging.level.root=INFO
logging.level.com.app.multiagent=DEBUG

## Logging for Spring AI chat-client advisors
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
